### ISSUE TITLE
terminates pipe if called inside

### ISSUE THREAD

**Issue by dlebedynskyi** [MadsMadsDk/gulp-tfs-checkout#1]
try
``` 
var tfs = require('gulp-tfs-checkout');

gulp.src(path.from.directives)
           .pipe(rename(path.deps.directives.file))
           .pipe(tfs()))
           .pipe(notify(WILL NEVER SEE '))
``` 
pipe gets terminated on tfs  step. pipe need to be available to continue work with file after tfs

**Comment by MadsMadsDk** [comment]
Hi!

I just tried this task:

    // TFS Checkout
    gulp.task('checkout', function() {
        return gulp.src([
            'Website/Layout/js/*',
            'Website/Layout/css/*'
        ])
        .pipe(tfs())
        .pipe(notify('Will never see'));
    });

It seems to be working fine. I'm using gulp-notify as my notify-module.

There seems to be a syntax error in your task. Can you try this, and tell me if you still get the error?

    gulp.src(path.from.directives)
           .pipe(rename(path.deps.directives.file))
           .pipe(tfs()))
           .pipe(notify('WILL NEVER SEE '));

Thanks!

**Comment by MadsMadsDk** [comment]
20 days with no response - I'm assuming this problem is solved. Reopen the issue if the problem persists.
