### ISSUE TITLE
Update tfs-unlock

### ISSUE THREAD

**Issue by antoniogarcez** [MadsMadsDk/gulp-tfs-checkout#10]
In my installation, I have the version 0.5.0 of tfs-unlock but I need the last version. 
How can I update tfs-unlock?

**Comment by MadsMadsDk** [comment]
Hi @antoniogarcez,

Try the following. In the directory, where you're using the package, try doing an `npm prune` and then `npm install --save-dev gulp-tfs-checkout`

Let me know if that does the trick.

**Comment by antoniogarcez** [comment]
Hi @MadsMadsDk,

It works! I thought that this update could improve the performance of your package in my computer but, it continues very slow.

Thanks anyway.

**Comment by MadsMadsDk** [comment]
Great. The speed may vary based on how many files you're trying to check out I think. There's probably also a lot of other things that matters in regard to speed, such as concurrent threads running as well as your machines specs. But I'm just guessing :)

Closing this!
