### ISSUE TITLE
Remove gulp-util dependency please

### ISSUE THREAD

**Issue by marlon-tucker** [MadsMadsDk/gulp-tfs-checkout#17]
Hello,

Gulp-Utils is being depreciated, see https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Looking at the code, it uses `PluginError` and `log`  so it should be a simple update to use these packages instead:

- `log` : https://www.npmjs.com/package/fancy-log
- `PluginError` : https://www.npmjs.com/package/plugin-error

**Comment by MadsMadsDk** [comment]
Fixed in `1.1.2`
