### ISSUE TITLE
Checkout does not acutally checkout file.

### ISSUE THREAD

**Issue by KhoaSydney** [MadsMadsDk/gulp-tfs-checkout#2]
I have the following task:

gulp.task('automatically-checkout-files', function () {
    return gulp.src(['./app/entities/**.ts'])
    .pipe(tfs());
});

after execute the task, it listed down all the files with checked out file "filename" etc but when I try to edit, it said access denied. and I can still see the lock icon next to the file in visual studio.

**Comment by MadsMadsDk** [comment]
Hello KhoaSydney,

The plugin is based on [tfs-unlock](https://github.com/danactive/tfs-unlock) which attempts to locate a Visual Studio installation in the following paths:

    // Enumeration for visualStudioPath
    paths = {
      vs2008: {
        "bit32": 'C:\\Program Files\\Microsoft Visual Studio 9.0\\Common7\\IDE\\',
        "bit64": 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\IDE\\'
      },
      vs2010: {
        "bit32": 'C:\\Program Files\\Microsoft Visual Studio 10.0\\Common7\\IDE\\',
        "bit64": 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\IDE\\'
      },
      vs2012: {
        "bit32": 'C:\\Program Files\\Microsoft Visual Studio 11.0\\Common7\\IDE\\',
        "bit64": 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\IDE\\'
      },
      vs2013: {
        "bit32": 'C:\\Program Files\\Microsoft Visual Studio 12.0\\Common7\\IDE\\',
        "bit64": 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\IDE\\'
      }
    };

If your installation is in another folder, it could cause problems, and would require an enhancement of tfs-unlock (one where you could set your own path to TFS).

Which version of Visual Studio are you using, and which path is your Visual Studio installed in?

**Comment by MadsMadsDk** [comment]
No further responses. I'll close this issue here.
