### ISSUE TITLE
gulp-tfs-checkout does not wait for the resolution of the unlock-tfs checkout() call

### ISSUE THREAD

**Issue by growlycode** [MadsMadsDk/gulp-tfs-checkout#3]
The unlock-tfs method "checkout" returns a promise. 
gulp-tfs-checkout doesn't wait for that promise to be resolved/rejected, just carries merrily on and logs that it has checked out the file, when in fact it may not have, either because it's yet to be completed, or because it's failed with some horrible error.

**Comment by MadsMadsDk** [comment]
Thanks for mentioning! I would love to fix it, but I don't have a tfs-server available any longer that I can test it on. I'd be happy to merge a pull-request though, if you have the time to fix it :)

**Comment by arangas** [comment]
I'm happy to test - I can easily repro this issue!

**Comment by fredbutters** [comment]
+1 I'm having this same issue.

**Comment by mikejr83** [comment]
I've submitted pull request #4 to fix the issue. I'm actually responsible for the issue. I submitted the patch to the upstream unlock-tfs project a year ago. For some reason the timing never caused a problem for us until the other day. MY BAD EVERYONE! <ducks />

**Comment by mikejr83** [comment]
@MadsMadsDk, would it be possible to bump the version number, and tag the commit? I can't remember if that is how npm will pick up the change or not.

**Comment by MadsMadsDk** [comment]
@mikejr83 I'm on it - I'll publish the changes shortly.

**Comment by mikejr83** [comment]
Great! Thanks!

**Comment by MadsMadsDk** [comment]
The fix should now be published. Remember to update your package to 1.0.1 :)

**Comment by arangas** [comment]
Works great, thanks!

**Comment by MadsMadsDk** [comment]
Great. I am closing this issue :)
