### ISSUE TITLE
Alert if file is locked by another user

### ISSUE THREAD

**Issue by fredbutters** [MadsMadsDk/gulp-tfs-checkout#5]
Currently the tfs.checkout() function runs, then logs the message 'Checked out file' + filename. Can it return a different message if that file is already locked by another user?

If you have any suggestions as to how I could change the plugin to include this feature I can try and test it with my TFS server. 

Thanks

**Comment by MadsMadsDk** [comment]
Hi @fredbutters.

I'm not quite sure what's possible to do or not. My suggestion would be to check out the plugin, which this gulp-wrapper is based on: https://github.com/danactive/tfs-unlock

That would be my starting point, in regards to figuring out how to notify the client, if the file is already locked by another user.

I hope I've understood the question :)

**Comment by fredbutters** [comment]
Yes, that's what I was asking for. The resolution of issue #3 added some error handling that includes this alert/warning if the file is already checked out. Thanks
