### ISSUE TITLE
tfs-unlock requires a peer of grunt@^0.4.5 but none was installed.

### ISSUE THREAD

**Issue by fredbutters** [MadsMadsDk/gulp-tfs-checkout#6]
I've been seeing this warning when running npm install. Nothing is failing but i there anything we can do about the warnings?

"npm WARN EPEERINVALID tfs-unlock@0.3.5 requires a peer of grunt@^0.4.5 but none was installed."

Thanks

**Comment by MadsMadsDk** [comment]
This could to be an issue with one of the depending plugins, namely tfs-unlock, or maybe have something to do with the lack of a grunt-installation - I can't tell.

Maybe the author of tfs-unlock can help here: https://github.com/danactive/tfs-unlock/issues

**Comment by Ranthalion** [comment]
Updating the tfs-unlock dependency in package.json to ^0.5.0 seems to resolve this warning.

**Comment by MadsMadsDk** [comment]
Updated package.json with a newer version of tfs-unlock, and published a new version to npm.
