### ISSUE TITLE
TFS check-in

### ISSUE THREAD

**Issue by mrvamsidhar** [MadsMadsDk/gulp-tfs-checkout#7]
Hello, Is there any way or any module to check-in a file using gulp modules?

**Comment by MadsMadsDk** [comment]
Not that I'm aware of - I also have a hard time seeing where such a module would be useful.
Also, this is out of scope of this particular plugin, and not anything I would introduce here.

**Comment by mrvamsidhar** [comment]
Thanks for your reply.

I am trying to do VSO build from gulp. Part of my requirement is, I need to update config xml file with some data before kicking build. I need to check-in this file once it is updated. Any better way?

**Comment by MadsMadsDk** [comment]
What kind of data are you trying to write to your config xml file? You might be able to to that with just node, which can manipulate files. Try looking into the File System API for node.js here: https://nodejs.org/dist/latest-v4.x/docs/api/fs.html

**Comment by mrvamsidhar** [comment]
Well, below is my config.xml. Attributes, android-versionCode,version values should always increment by 1.

So Instead of my self updating and then check-in. By build command should increment and then check-in. - This is what I am trying to achieve.

`<?xml version='1.0' encoding='utf-8'?>
<widget **android-versionCode="881454"** defaultlocale="en-US" id="com.geico.adexpress.DEV111"** version="1.35.56"** xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http:inject//cordova.apache.org/ns/1.0" xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps">

**Comment by MadsMadsDk** [comment]
Maybe [this blogpost](http://www.jayway.com/2015/03/11/automatic-versioncode-generation-in-android-gradle/) can help you solve your problem :)

**Comment by mrvamsidhar** [comment]
Thanks for your reply. I am developing Hybrid Mobile application using Visual Studio TACO. I dont have much knowledge on gradle. I will look in to it. 
I am having a question here. Lets say I modified Versioncode and version name some how in config.xml file. Still I some how need to check-in this  modified file. Correct?
 Please correct me if I am wrong here. I started doubting my approach. I just written this simple method to check-in

`function checkinFile(comment, cb) {
    var defered = $q.defer();
    var exec = require('child_process').exec;
    var filePath = process.cwd() + "\\config.xml";
    exec('tf checkin /noprompt /comment:' + (comment || '') + ' ' + filePath, function (error, stdout, stderr) {
        if (error !== null) {
            console.log('Error in checking in config.xml file....');
            cb(error);
            defered.reject(error);
        } else {
            console.log('config.xml checked-in successfully.');
            cb(stdout);
            defered.resolve(stdout);
        }
    });
    return defered.promise;
}`

**Comment by MadsMadsDk** [comment]
Closing this, as it is not a relevant issue to this plugin.
