### ISSUE TITLE
Unable to checkout issue

### ISSUE THREAD

**Issue by bmihestean** [MadsMadsDk/gulp-tfs-checkout#8]
Hello,

I'm still having the 
"Unable to checkout "": Check that this file is under source control and tf.exe works properly with this file." issue when trying to checkout 3 files from TFS.

`gulp.task('checkout', function () {
    return gulp.src([
        './bower.json',
        './package.json',
        './app/commons/factories/factoriesModule.js'
    ])
        .pipe(tfs());
});`
then:
`gulp.task('feature', "Increment the MINOR version number.", ['checkout'], function () {
    return startVersionIncrement('minor');
});`

Am I missing anything here? 

Thanks.

**Comment by MadsMadsDk** [comment]
Hi! Sorry I haven't gotten back to you sooner.
What version of TFS are you using? I think I might be able to fix it with an updated dependency. Worth a try.

**Comment by MadsMadsDk** [comment]
Please update to `gulp-tfs-checkout@1.0.3` - let me know if that doesn't resolve the issue.

**Comment by ebitauld** [comment]
I got the same in 1.0.3
Please, help me!

**Comment by zurie** [comment]
I fixed this issue for myself with VS 2017...    the issue I had was that I have VS 2013 VS 2015 and VS 2017 on my PC,  it was trying to use TF.exe from 2015?   

there is a PATH that is now optional in tfs-unlock, which is a dependancy this plugin uses.  I had to manually go into my node_modules / gulp-tfs-checkout  index.js  and change this line...

tfs.init();

you have to make it.

            tfs.init({
                visualStudioPath: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\'
            });

assuming you are using VS 2017.   it will find the correct TF.exe and check out files

**Comment by Korneffstyle** [comment]
Hi, I have the same issue.
Solution from zurie did not help.
Visual Studio Enterprise 2017
![clipboard03](https://user-images.githubusercontent.com/41143677/42622147-633c5276-85c8-11e8-9951-8549bd7f9604.jpg)

![clipboard04](https://user-images.githubusercontent.com/41143677/42622156-684574fa-85c8-11e8-9c4c-beb76eea7513.jpg)

**Comment by MadsMadsDk** [comment]
Merged this issue, and will be publishing the fix today.
